version: '3.3'

services:

  tf012aws2:
    build:
        context: .
        dockerfile: ./docker/Dockerfile
    env_file: .env
    working_dir: /code
    volumes:
        - .:/code
        - ~/.aws:/root/.aws
