name: Docker Image CI

on:
  push:
    branches: [ LuizFDS/CI/CD ]
  pull_request:
    branches: [ LuizFDS/CI/CD ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        AWS_PROFILE: 
        AWS_ACCESS_ID: ${{ secrets.AWS_ACCESS_ID }}
        AWS_SECRET_ACCESS: ${{ secrets.AWS_SECRET_ACCESS }}
        TF_VAR_project_name: wdpress-dev
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_ID }}" && \
        export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS }}" && \
        export AWS_DEFAULT_REGION="ap-southeast-2" && \
        make plan && make build
