name: Docker Image CI

on:
  push:
    branches: [ LuizFDS/CI/CD ]
  pull_request:
    branches: [ LuizFDS/CI/CD ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        AWS_ACCESS_ID: ${{ secrets.AWS_ACCESS_ID }}
        AWS_SECRET_ACCESS: ${{ secrets.AWS_SECRET_ACCESS }}
        TF_VAR_project_name: wdpress-dev
      run:  aws configure set aws_access_key_id ${AWS_ACCESS_ID} && \
            aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS} && \
            make build
