name: Docker Image CI

on:
  push:
    branches: [ LuizFDS/CI/CD ]
  pull_request:
    branches: [ LuizFDS/CI/CD ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 ls && aws configure list
