name: Docker Image CI

on:
  push:
    branches: [ LuizFDS/CI/CD ]
  pull_request:
    branches: [ LuizFDS/CI/CD ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS }}
    
    - name: Build the Docker image
      uses: actions/checkout@v2
      env:
        AWS_PROFILE
        TF_VAR_project_name: wdpress-dev
      run:  echo ${AWS_ACCESS_ID} && \
            aws configure set aws_access_key_id ${AWS_ACCESS_ID} && \
            aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS} && \
            make build
