name: Docker Image CI

on:
  push:
    branches: [ LuizFDS/CI/CD ]
    paths:
      - docker/wordpress/*
  pull_request:
    branches: [ master ]
    paths:
      - docker/wordpress/*

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-southeast-2"
        run: |
          make plan && make build
